services:
  mysql:
    image: mysql:8.0
    container_name: gateway_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pagamentos
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10

  keycloak:
    image: quay.io/keycloak/keycloak:23.0.0
    container_name: gateway_keycloak
    command: start-dev --import-realm
    environment:
      KC_DB: dev-file
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8180:8080"
    volumes:
      - ./src/main/resources/keycloack/realm-export.json:/opt/keycloak/data/import/realm.json
    depends_on:
      mysql:
        condition: service_healthy

volumes:
  mysql_data: